name: 部署到 GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - uses: pnpm/setup@v2
        with:
          version: 12
          runtime: node@24

      - run: pnpm install
      
      - run: pnpm run build

      - uses: actions/upload-pages-artifact@v5
        with:
          path: build

  deploy:
    name: 部署
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
